services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: simple-api-keycloak
    command:
      - start-dev
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "127.0.0.1:8180:8080"
    volumes:
      - ./deploy/keycloak/realm-local-dev.json:/opt/keycloak/data/import/realm-local-dev.json:ro
      - keycloak_data:/opt/keycloak/data

volumes:
  keycloak_data:
